bitbag_sylius_wishlist_plugin_shop_wishlist_list_products:
    path: /wishlist
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.list_wishlist_products

bitbag_sylius_wishlist_plugin_shop_wishlist_add_product:
    path: /wishlist/add/{productId}
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.add_product_to_wishlist

bitbag_sylius_wishlist_plugin_shop_wishlist_remove_product:
    path: /wishlist/remove/{productId}
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.remove_product_from_wishlist

bitbag_sylius_wishlist_plugin_shop_wishlist_add_product_variant:
    path: /wishlist/add/variant/{variantId}
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.add_product_variant_to_wishlist

bitbag_sylius_wishlist_plugin_shop_wishlist_remove_product_variant:
    path: /wishlist/{wishlistId}/remove/variant/{variantId}
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.remove_product_variant_from_wishlist

bitbag_sylius_wishlist_plugin_shop_wishlist_render_header_template:
    path: /wishlist/header-template
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.render_header_template

bitbag_sylius_wishlist_plugin_shop_wishlist_clean:
    path: /wishlist/clear/{wishlistId}
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.clean_wishlist

bitbag_sylius_wishlist_plugin_shop_wishlist_create_new_wishlist:
    path: /wishlists/new
    methods: [GET, POST]
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.wishlist:createAction
        _sylius:
            template: '@BitBagSyliusWishlistPlugin/CreateWishlist/index.html.twig'
            form:
                type: BitBag\SyliusWishlistPlugin\Form\Type\CreateNewWishlistType
            redirect:
                route: bitbag_sylius_wishlist_plugin_shop_wishlist_list_wishlists

bitbag_sylius_wishlist_plugin_shop_wishlist_remove_wishlist:
    path: /wishlists/{id}/remove
    methods: [GET, POST, DELETE]
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.wishlist:deleteAction
        _sylius:
            csrf_protection: false
            redirect:
                route: bitbag_sylius_wishlist_plugin_shop_wishlist_list_wishlists

bitbag_sylius_wishlist_plugin_shop_wishlist_edit_wishlist_name:
    path: /wishlists/{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.wishlist:updateAction
        _sylius:
            template: '@BitBagSyliusWishlistPlugin/CreateWishlist/index.html.twig'
            form:
                type: BitBag\SyliusWishlistPlugin\Form\Type\CreateNewWishlistType
            redirect:
                route: bitbag_sylius_wishlist_plugin_shop_wishlist_list_wishlists

bitbag_sylius_wishlist_plugin_shop_wishlist_list_wishlists:
    path: /wishlists
    methods: [GET]
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.wishlist:indexAction
        _sylius:
            template: '@BitBagSyliusWishlistPlugin/WishlistGroup/index.html.twig'

bitbag_sylius_wishlist_plugin_shop_wishlist_show_chosen_wishlist:
    path: /wishlists/{wishlistId}
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.show_chosen_wishlist

bitbag_sylius_wishlist_plugin_shop_wishlist_add_product_to_selected_wishlist:
    path: /wishlist/{wishlistId}/add/{productId}
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.add_product_to_selected_wishlist
